language: php

branches:
  only:
    - master

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: nightly
    - php: 7.1
      env: COVERAGE=yes
    - php: 7.1
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    - php: 7.2
      env: PHPSTAN=yes
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - if [ "$TRAVIS_PHP_VERSION" != "nightly" ] && [ "$COVERAGE" != "yes" ]; then phpenv config-rm xdebug.ini; fi;
  - composer self-update
  - echo 'zend.assertions=1' > $HOME/.phpenv/versions/$(phpenv version-name)/etc/conf.d/assert.ini

install: |
  composer update $COMPOSER_FLAGS --prefer-dist --no-interaction

  if [ "$PHPSTAN" = "yes" ]; then
    composer require --dev phpstan/phpstan:^0.10.1
  fi

script:
  - |
    if [ -f vendor/bin/phpstan ]; then
      vendor/bin/phpstan analyse -c .phpstan.neon
    fi
  - |
    if [ "$COVERAGE" = "yes" ]; then
      vendor/bin/phpunit --verbose --coverage-clover=coverage.clover --coverage-text
      phpenv config-rm xdebug.ini
      vendor/bin/php-cs-fixer fix --diff --dry-run
    else
      vendor/bin/phpunit --verbose
    fi

after_script: if [ "$COVERAGE" = "yes" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
